pipeline:
  name: k8s-ui-remote
  identifier: k8suiremote
  tags: {}
  template:
    templateRef: PipelineTemplateUI
    versionLabel: v1
    templateInputs:
      stages:
        - parallel:
            - stage:
                identifier: deploytest
                type: Deployment
                spec:
                  environment:
                    infrastructureDefinitions:
                      - identifier: k8s_ui_2
                        inputs:
                          identifier: k8s_ui_2
                          type: KubernetesGcp
                          spec:
                            cluster: <+input>
                            project: <+input>
  projectIdentifier: DoNotDelete_TestAbhi
  orgIdentifier: Ng_Pipelines_K8s_Organisations
