pipeline:
  projectIdentifier: DoNotDelete_TestAbhi
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: deploy-test
        identifier: deploytest
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8s
          environment:
            environmentRef: k8sEnv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8s_ui_2
                inputs:
                  identifier: k8s_ui_2
                  type: KubernetesGcp
                  spec:
                    cluster: <+input>
                    project: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: printKubeConfig
                  identifier: kubectlVersionPrint
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: "export KUBECONFIG=${HARNESS_KUBE_CONFIG_PATH}\n\n\
                          echo \"$KUBECONFIG\"\nprintf \"\\n---------------------\\\
                          n\"\ncat $KUBECONFIG\n\nif test -z \"$KUBECONFIG\" \nthen\n\
                          \      printg \"\\n\\$KUBECONFIG is empty\"\n      exit\
                          \ 1\nelse\n      printf \"\\nOK - \\$KUBECONFIG is NOT empty\"\
                          \nfi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_2
                  identifier: K8sRollingDeploy_2
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
                contextType: Pipeline
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Retry
                spec:
                  retryCount: 1
                  retryIntervals:
                    - 10s
                  onRetryFailure:
                    action:
                      type: MarkAsFailure
        variables:
          - name: resourceNamePrefix
            type: String
            description: ""
            required: false
            value: sample-k8s-yh
        delegateSelectors:
          - abhi-gcp-oidc-test-delegate
    - stage:
        name: stage2
        identifier: stage2
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            useFromStage:
              stage: deploytest
          environment:
            useFromStage:
              stage: deploytest
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: "export KUBECONFIG=${HARNESS_KUBE_CONFIG_PATH}\n\n\
                          echo \"$KUBECONFIG\"\nprintf \"\\n---------------------\\\
                          n\"\ncat $KUBECONFIG\n\nif test -z \"$KUBECONFIG\" \nthen\n\
                          \      printg \"\\n\\$KUBECONFIG is empty\"\n      exit\
                          \ 1\nelse\n      printf \"\\nOK - \\$KUBECONFIG is NOT empty\"\
                          \nfi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_1
                  identifier: K8sRollingDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
            rollbackSteps:
              - step:
                  type: K8sRollingRollback
                  name: K8sRollingRollback_1
                  identifier: K8sRollingRollback_1
                  spec:
                    pruningEnabled: false
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  variables:
    - name: timeout
      type: String
      description: ""
      value: 10m
    - name: manifestPath
      type: String
      description: ""
      value: deployment.yaml
    - name: _true
      type: String
      description: ""
      value: "true"
    - name: _True
      type: String
      description: ""
      value: "True"
    - name: _TRUE
      type: String
      description: ""
      value: "TRUE"
    - name: _false
      type: String
      description: ""
      value: "false"
    - name: _False
      type: String
      description: ""
      value: "False"
    - name: _FALSE
      type: String
      description: ""
      value: "FALSE"
    - name: instances
      type: Number
      description: ""
      value: 2
    - name: instances_pct
      type: Number
      description: ""
      value: 100
    - name: workloadName
      type: String
      description: ""
      value: Deployment/<+stage.variables.resourceNamePrefix>-deployment
    - name: resourceName
      type: String
      description: ""
      value: Deployment/<+stage.variables.resourceNamePrefix>-deployment
    - name: populatedManifestPath
      type: String
      description: ""
      value: templates/deployment-k8s.yaml
    - name: manifestPath2
      type: String
      description: ""
      value: deployment.yaml
    - name: populatedManifestPath2
      type: String
      description: ""
      value: deployment.yaml
    - name: projectName
      type: String
      description: ""
      required: false
      value: qa-target
    - name: clusterName
      type: String
      description: ""
      required: false
      value: us-central1-c/qa-target
  timeout: 10m
  identifier: k8suiremote
  name: k8s-ui-remote
